default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: wainavi_development

test:
  <<: *default
  host: localhost
  database: wainavi_test

production:
  <<: *default
  database: wainavi_production
  username: wainavi
  host: <%= ENV["WAINAVI_DATABASE_HOST"] %>
  password: <%= ENV["WAINAVI_DATABASE_PASSWORD"] %>
