class WineRegion < ActiveHash::Base
  self.data = [
    { id: 1, name: '北海道 / 北海道' },
    { id: 2, name: '東北 / 青森県' },
    { id: 3, name: '東北 / 岩手県' },
    { id: 4, name: '東北 / 宮城県' },
    { id: 5, name: '東北 / 秋田県' },
    { id: 6, name: '東北 / 山形県' },
    { id: 7, name: '東北 / 福島県' },
    { id: 8, name: '関東 / 茨城県' },
    { id: 9, name: '関東 / 栃木県' },
    { id: 10, name: '関東 / 群馬県' },
    { id: 11, name: '関東 / 埼玉県' },
    { id: 12, name: '関東 / 千葉県' },
    { id: 13, name: '関東 / 東京都' },
    { id: 14, name: '関東 / 神奈川県' },
    { id: 15, name: '甲信越・北陸 / 新潟県' },
    { id: 16, name: '甲信越・北陸 / 富山県' },
    { id: 17, name: '甲信越・北陸 / 石川県' },
    { id: 18, name: '甲信越・北陸 / 福井県' },
    { id: 19, name: '甲信越・北陸 / 山梨県' },
    { id: 20, name: '甲信越・北陸 / 長野県' },
    { id: 21, name: '東海 / 岐阜県' },
    { id: 22, name: '東海 / 静岡県' },
    { id: 23, name: '東海 / 愛知県' },
    { id: 24, name: '東海 / 三重県' },
    { id: 25, name: '近畿 / 滋賀県' },
    { id: 26, name: '近畿 / 京都府' },
    { id: 27, name: '近畿 / 大阪府' },
    { id: 28, name: '近畿 / 兵庫県' },
    { id: 29, name: '近畿 / 奈良県' },
    { id: 30, name: '近畿 / 和歌山県' },
    { id: 31, name: '中国 / 鳥取県' },
    { id: 32, name: '中国 / 島根県' },
    { id: 33, name: '中国 / 岡山県' },
    { id: 34, name: '中国 / 広島県' },
    { id: 35, name: '中国 / 山口県' },
    { id: 36, name: '四国 / 徳島県' },
    { id: 37, name: '四国 / 香川県' },
    { id: 38, name: '四国 / 愛媛県' },
    { id: 39, name: '四国 / 高知県' },
    { id: 40, name: '九州・沖縄 / 福岡県' },
    { id: 41, name: '九州・沖縄 / 佐賀県' },
    { id: 42, name: '九州・沖縄 / 長崎県' },
    { id: 43, name: '九州・沖縄 / 熊本県' },
    { id: 44, name: '九州・沖縄 / 大分県' },
    { id: 45, name: '九州・沖縄 / 宮崎県' },
    { id: 46, name: '九州・沖縄 / 鹿児島県' },
    { id: 47, name: '九州・沖縄 / 沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :wineries
end